######################################################################
# Automatically generated by qmake (3.1) Thu Feb 22 17:11:57 2024
######################################################################

QT += core gui
QT += network


greaterThan(QT_MAJOR_VERSION, 4): QT += widgets


SOURCES += \
    main.cpp\
    mainwindow.cpp\
    crypt.cpp

HEADERS += mainwindow.h
HEADERS += crypt.h


 
